name: Terraform
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.2 # Replace with desired Terraform version
    - name: Run Terraform
      env:
        ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        USER: ${{ secrets.SNOWFLAKE_USER }}
        PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      run: |
        export ACCOUNT=$ACCOUNT
        export USER=$USER
        export PASSWORD=$PASSWORD
        terraform init
        terraform plan
        terraform apply --auto-approve
