name: Terraform
on:
  push:
    branches:
      - main
  workflow_dispatch:
   inputs:
     db:
        description: db details
        required: true
     ws:
        description: db details
        required: true
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.2 # Replace with desired Terraform version
    - name: Run Terraform
      env:
        ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        USER: ${{ secrets.SNOWFLAKE_USER }}
        PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        DB: ${{ github.event.inputs.db }}
        ws: ${{ github.event.inputs.ws }}
      run: |
        export TF_VAR_ACCOUNT=$ACCOUNT
        export TF_VAR_USER=$USER
        export TF_VAR_PASSWORD=$PASSWORD
        export TF_VAR_DB=$DB
        export TF_VAR_WS=$WS
        terraform init
        terraform plan
        terraform apply --auto-approve
